name: Generate snake

on:
  schedule:
    - cron: "0 0 * * *"   # daily
  workflow_dispatch:       # allows manual run from Actions tab

permissions:
  contents: write          # REQUIRED so it can commit dist/ files

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: xanboy
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Push generated files
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist"
          message: "chore: update contribution snake"
